dev: true
service:
  type: NodePort
  ports:
    http_port: 30841
    debug_port: 30842
deployment:
  replicas: 1
  strategy: {}
  affinity: {}
  nodeSelector: {}
  tolerations: []
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 100Mi
      cpu: 100m
apps:
  port: 8001
  broker_host: kafka-broker
  broker_port: 9092
  topic_name: tweety
  request_per_conn: 5
  compression_type: snappy
  linger_ms: 20
  batch_size_kb: 32
  retry_backoff_ms: 100
  delivery_time_out_ms: 120000
  rest_produce: /produce
image: samutup/kafka-twitter:1.0.0